export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  image: string;
  rating: number;
  reviewCount: number;
  prepTime: string;
  isAvailable: boolean;
  isPopular: boolean;
  isFeatured: boolean;
  calories?: number;
  tags?: string[];
}

export interface Order {
  id: string;
  items: { name: string; quantity: number; price: number }[];
  total: number;
  status: 'pending' | 'preparing' | 'ready' | 'delivered' | 'cancelled';
  createdAt: string;
  paymentMethod: 'on_delivery' | 'momo';
  pickupTime: string;
  customerName?: string;
}

export interface Notification {
  id: string;
  title: string;
  body: string;
  time: string;
  read: boolean;
  type: 'order' | 'promo' | 'info';
}

export const categories = [
  { id: 'all', name: 'All', icon: '🍽️' },
  { id: 'rice', name: 'Rice Dishes', icon: '🍚' },
  { id: 'soups', name: 'Soups & Stews', icon: '🍲' },
  { id: 'fastfood', name: 'Fast Food', icon: '🍔' },
  { id: 'snacks', name: 'Snacks', icon: '🥪' },
  { id: 'drinks', name: 'Drinks', icon: '🥤' },
  { id: 'breakfast', name: 'Breakfast', icon: '🍳' },
];

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Jollof Rice + Chicken',
    description:
      'Aromatic tomato-based rice slow-cooked with spices, served with juicy grilled or fried chicken. HTU\'s most-loved dish!',
    price: 35,
    category: 'Rice Dishes',
    image: 'https://loremflickr.com/400/300/jollof,rice?lock=1',
    rating: 4.8,
    reviewCount: 214,
    prepTime: '15–20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    calories: 680,
    tags: ['Popular', 'Staff Pick'],
  },
  {
    id: '2',
    name: 'Jollof Rice + Fish',
    description:
      'Classic tomato jollof rice paired with crispy fried tilapia or mackerel. A cafeteria staple.',
    price: 28,
    category: 'Rice Dishes',
    image: 'https://loremflickr.com/400/300/rice,fish?lock=2',
    rating: 4.6,
    reviewCount: 187,
    prepTime: '15–20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 600,
    tags: ['Popular'],
  },
  {
    id: '3',
    name: 'Fried Rice + Chicken',
    description:
      'Golden stir-fried rice with vegetables, eggs, and seasoning, served with tender chicken.',
    price: 38,
    category: 'Rice Dishes',
    image: 'https://loremflickr.com/400/300/fried,rice?lock=3',
    rating: 4.7,
    reviewCount: 163,
    prepTime: '15–20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    calories: 720,
    tags: ['Popular'],
  },
  {
    id: '4',
    name: 'Waakye',
    description:
      'Traditional Ghanaian rice and beans cooked together, served with spaghetti, wele, and fish stew. A national favourite!',
    price: 22,
    category: 'Rice Dishes',
    image: 'https://loremflickr.com/400/300/rice,beans?lock=4',
    rating: 4.9,
    reviewCount: 289,
    prepTime: '10–15 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    calories: 580,
    tags: ['Popular', 'Best Value'],
  },
  {
    id: '5',
    name: 'Plain Rice + Stew',
    description:
      'Fluffy plain white rice served with rich tomato stew. Simple, filling, and affordable.',
    price: 20,
    category: 'Rice Dishes',
    image: 'https://loremflickr.com/400/300/rice,stew?lock=5',
    rating: 4.4,
    reviewCount: 98,
    prepTime: '10 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 520,
    tags: ['Best Value'],
  },
  {
    id: '6',
    name: 'Banku + Tilapia',
    description:
      'Fermented corn and cassava dough served with grilled whole tilapia, garden egg stew, and shito (pepper sauce). A true Ghanaian delicacy.',
    price: 45,
    category: 'Soups & Stews',
    image: 'https://loremflickr.com/400/300/grilled,tilapia?lock=6',
    rating: 4.9,
    reviewCount: 312,
    prepTime: '20–25 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: true,
    calories: 750,
    tags: ['Popular', 'Staff Pick'],
  },
  {
    id: '7',
    name: 'Fufu + Light Soup',
    description:
      'Hand-pounded cassava and plantain fufu served with spicy chicken light soup. Comfort in a bowl.',
    price: 40,
    category: 'Soups & Stews',
    image: 'https://loremflickr.com/400/300/soup,chicken?lock=7',
    rating: 4.8,
    reviewCount: 241,
    prepTime: '20–25 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 700,
    tags: ['Popular'],
  },
  {
    id: '8',
    name: 'Fufu + Palmnut Soup',
    description:
      'Smooth fufu served with rich, creamy palmnut (banga) soup cooked with goat meat or chicken.',
    price: 42,
    category: 'Soups & Stews',
    image: 'https://loremflickr.com/400/300/palm,soup?lock=8',
    rating: 4.9,
    reviewCount: 267,
    prepTime: '20–25 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 780,
    tags: ['Popular', 'Chef\'s Choice'],
  },
  {
    id: '9',
    name: 'Omotuo + Groundnut Soup',
    description:
      'Soft rice balls served with thick, nutty groundnut (peanut) soup, garnished with chicken.',
    price: 38,
    category: 'Soups & Stews',
    image: 'https://loremflickr.com/400/300/groundnut,soup?lock=9',
    rating: 4.7,
    reviewCount: 178,
    prepTime: '20–25 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 720,
    tags: [],
  },
  {
    id: '10',
    name: 'Fried Chicken + Chips',
    description:
      'Crispy seasoned fried chicken pieces served with golden french fries and ketchup.',
    price: 45,
    category: 'Fast Food',
    image: 'https://loremflickr.com/400/300/fried,chicken?lock=10',
    rating: 4.6,
    reviewCount: 145,
    prepTime: '15–20 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 820,
    tags: ['Popular'],
  },
  {
    id: '11',
    name: 'Meat Pie',
    description:
      'Flaky pastry filled with seasoned minced meat and vegetables. Great for a quick bite.',
    price: 12,
    category: 'Fast Food',
    image: 'https://loremflickr.com/400/300/meat,pie?lock=11',
    rating: 4.3,
    reviewCount: 89,
    prepTime: '5 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 280,
    tags: ['Quick Bite'],
  },
  {
    id: '12',
    name: 'Spring Rolls (3 pcs)',
    description:
      'Crispy golden spring rolls filled with vegetables and chicken, served with sweet chili sauce.',
    price: 22,
    category: 'Fast Food',
    image: 'https://loremflickr.com/400/300/spring,rolls?lock=12',
    rating: 4.5,
    reviewCount: 112,
    prepTime: '10 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 320,
    tags: [],
  },
  {
    id: '13',
    name: 'Kelewele',
    description:
      'Spiced ripe plantain cubes deep-fried to perfection. Seasoned with ginger, pepper, and spices.',
    price: 15,
    category: 'Snacks',
    image: 'https://loremflickr.com/400/300/plantain,fried?lock=13',
    rating: 4.7,
    reviewCount: 203,
    prepTime: '10 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 380,
    tags: ['Popular', 'Vegan'],
  },
  {
    id: '14',
    name: 'Koose (Bean Cakes)',
    description:
      'Fried bean cakes made from black-eyed peas, crispy outside and soft inside. Served with pepper.',
    price: 8,
    category: 'Snacks',
    image: 'https://loremflickr.com/400/300/bean,fritters?lock=14',
    rating: 4.4,
    reviewCount: 76,
    prepTime: '5 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 210,
    tags: ['Vegan', 'Best Value'],
  },
  {
    id: '15',
    name: 'Club Sandwich',
    description:
      'Triple-layered sandwich with grilled chicken, lettuce, tomato, egg, and mayo on toasted bread.',
    price: 25,
    category: 'Snacks',
    image: 'https://loremflickr.com/400/300/club,sandwich?lock=15',
    rating: 4.5,
    reviewCount: 134,
    prepTime: '5–10 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 450,
    tags: [],
  },
  {
    id: '16',
    name: 'Sobolo',
    description:
      'Refreshing chilled hibiscus (roselle) drink with ginger and cloves. Ghana\'s beloved natural juice.',
    price: 8,
    category: 'Drinks',
    image: 'https://loremflickr.com/400/300/hibiscus,drink?lock=16',
    rating: 4.8,
    reviewCount: 319,
    prepTime: '1–2 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 45,
    tags: ['Popular', 'Vegan'],
  },
  {
    id: '17',
    name: 'Mineral (Coke/Fanta/Sprite)',
    description: 'Cold bottled soft drink. Choose from Coca-Cola, Fanta Orange, or Sprite.',
    price: 8,
    category: 'Drinks',
    image: 'https://loremflickr.com/400/300/cold,soda?lock=17',
    rating: 4.5,
    reviewCount: 201,
    prepTime: '1 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 140,
    tags: [],
  },
  {
    id: '18',
    name: 'Malta Guiness',
    description:
      'Non-alcoholic malt drink, sweet and nourishing. A cafeteria classic.',
    price: 12,
    category: 'Drinks',
    image: 'https://loremflickr.com/400/300/malt,beverage?lock=18',
    rating: 4.6,
    reviewCount: 167,
    prepTime: '1 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 190,
    tags: [],
  },
  {
    id: '19',
    name: 'Fresh Fruit Yoghurt',
    description:
      'Creamy chilled yoghurt with fresh fruit toppings. Healthy and delicious.',
    price: 15,
    category: 'Drinks',
    image: 'https://loremflickr.com/400/300/yogurt,fruit?lock=19',
    rating: 4.7,
    reviewCount: 98,
    prepTime: '2 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 160,
    tags: ['Healthy'],
  },
  {
    id: '20',
    name: 'Pure Water (Sachet)',
    description: 'Cold chilled sachet water. Refreshing and budget-friendly.',
    price: 2,
    category: 'Drinks',
    image: 'https://loremflickr.com/400/300/water,bottle?lock=20',
    rating: 5.0,
    reviewCount: 543,
    prepTime: '1 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 0,
    tags: ['Best Value'],
  },
  {
    id: '21',
    name: 'Hausa Koko + Bread',
    description:
      'Warm, spicy millet porridge served with sliced bread. The perfect morning energy boost.',
    price: 15,
    category: 'Breakfast',
    image: 'https://loremflickr.com/400/300/porridge,breakfast?lock=21',
    rating: 4.8,
    reviewCount: 187,
    prepTime: '5 min',
    isAvailable: true,
    isPopular: true,
    isFeatured: false,
    calories: 380,
    tags: ['Popular', 'Morning Special'],
  },
  {
    id: '22',
    name: 'Bread + Egg (Boiled/Fried)',
    description:
      'Sliced bread served with boiled or fried eggs. Simple, nutritious, and filling.',
    price: 18,
    category: 'Breakfast',
    image: 'https://loremflickr.com/400/300/bread,eggs?lock=22',
    rating: 4.6,
    reviewCount: 143,
    prepTime: '5–10 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 320,
    tags: ['Morning Special'],
  },
  {
    id: '23',
    name: 'Tea + Bread',
    description:
      'Hot Lipton tea served with fresh bread and butter or margarine. Classic morning comfort.',
    price: 12,
    category: 'Breakfast',
    image: 'https://loremflickr.com/400/300/tea,toast?lock=23',
    rating: 4.5,
    reviewCount: 112,
    prepTime: '5 min',
    isAvailable: true,
    isPopular: false,
    isFeatured: false,
    calories: 280,
    tags: ['Morning Special', 'Best Value'],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'HTU00145',
    items: [
      { name: 'Jollof Rice + Chicken', quantity: 1, price: 35 },
      { name: 'Sobolo', quantity: 2, price: 8 },
    ],
    total: 51,
    status: 'ready',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    paymentMethod: 'on_delivery',
    pickupTime: '12:30',
    customerName: 'Kwesi Mensah',
  },
  {
    id: 'HTU00144',
    items: [
      { name: 'Banku + Tilapia', quantity: 1, price: 45 },
    ],
    total: 45,
    status: 'preparing',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    paymentMethod: 'momo',
    pickupTime: '1:00 PM',
    customerName: 'Ama Boateng',
  },
  {
    id: 'HTU00143',
    items: [
      { name: 'Waakye', quantity: 2, price: 22 },
      { name: 'Malta Guiness', quantity: 2, price: 12 },
    ],
    total: 68,
    status: 'delivered',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    paymentMethod: 'momo',
    pickupTime: '11:00 AM',
    customerName: 'Kwesi Mensah',
  },
  {
    id: 'HTU00142',
    items: [
      { name: 'Fufu + Palmnut Soup', quantity: 1, price: 42 },
      { name: 'Pure Water (Sachet)', quantity: 2, price: 2 },
    ],
    total: 46,
    status: 'delivered',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    paymentMethod: 'on_delivery',
    pickupTime: '12:00 PM',
    customerName: 'Kwesi Mensah',
  },
  {
    id: 'HTU00141',
    items: [
      { name: 'Fried Rice + Chicken', quantity: 1, price: 38 },
      { name: 'Mineral (Coke/Fanta/Sprite)', quantity: 1, price: 8 },
    ],
    total: 46,
    status: 'cancelled',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    paymentMethod: 'momo',
    pickupTime: '2:00 PM',
    customerName: 'Kwesi Mensah',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Order Ready! 🎉',
    body: 'Your order #HTU00145 is ready for pickup. Come collect your meal at the counter.',
    time: '10 min ago',
    read: false,
    type: 'order',
  },
  {
    id: '2',
    title: 'Order Confirmed',
    body: 'Your order #HTU00144 has been confirmed and is being prepared. Estimated time: 20 min.',
    time: '35 min ago',
    read: false,
    type: 'order',
  },
  {
    id: '3',
    title: 'Weekend Special 🔥',
    body: 'Enjoy 20% off all drinks this Saturday! Use code WEEKEND20 at checkout.',
    time: '2 hours ago',
    read: true,
    type: 'promo',
  },
  {
    id: '4',
    title: 'New Menu Item!',
    body: 'We\'ve added Waakye Special with extra toppings. Try it today for just ₵28!',
    time: '1 day ago',
    read: true,
    type: 'info',
  },
  {
    id: '5',
    title: 'Order Delivered ✅',
    body: 'Your order #HTU00143 has been picked up. Enjoy your meal!',
    time: '2 days ago',
    read: true,
    type: 'order',
  },
  {
    id: '6',
    title: 'Cafeteria Hours Update',
    body: 'The cafeteria will be open from 7:00 AM to 7:00 PM on weekdays. No service on Sundays.',
    time: '3 days ago',
    read: true,
    type: 'info',
  },
];
